// Build the browser Core and the ordered v2 feature sources.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { buildSync } from 'esbuild';

const root = fileURLToPath(new URL('../', import.meta.url));
export const v2FeatureNames = [
  "shell/state.js",
  "discovery/registry.js",
  "proof/storage.js",
  "shell/format.js",
  "recovery/journal.js",
  "launch/distribution.js",
  "wallet/solflare.js",
  "shell/presentation.js",
  "launch/progress.js",
  "shell/dialogs.js",
  "launch/logo.js",
  "launch/config.js",
  "recovery/plan.js",
  "launch/workspace.js",
  "launch/vanity.js",
  "launch/pool-editor.js",
  "proof/evidence.js",
  "proof/classic-artifact.js",
  "proof/compare.js",
  "proof/report-data.js",
  "proof/report-html.js",
  "launch/funding-view.js",
  "launch/ledger.js",
  "launch/finalization-view.js",
  "launch/activity.js",
  "launch/readiness.js",
  "proof/replacement-audit.js",
  "wallet/view.js",
  "discovery/view.js",
  "shell/settings.js",
  "recovery/view.js",
  "shell/render.js",
  "launch/funding.js",
  "proof/export.js",
  "launch/actions.js",
  "wallet/actions.js",
  "recovery/sweep.js",
  "launch/prepare.js",
  "wallet/destinations.js",
  "discovery/coins.js",
  "launch/support.js",
  "launch/execute.js",
  "shell/connection.js",
  "recovery/actions.js",
  "shell/events.js",
  "launch/quick.js",
  "shell/startup.js"
];
export const v2FeaturePaths = v2FeatureNames.map((name) => path.join(root, 'public/v2/features', name));
export const v2AppPath = path.join(root, 'public/v2/app.js');
export const browserCorePath = path.join(root, 'public/v2/core.js');

export function buildV2AppString() {
  return '// Generated by npm run build:js from public/v2/features/.\n'
    + v2FeaturePaths.map((file) => readFileSync(file, 'utf8')).join('\n');
}

export function buildBrowserCoreString() {
  return buildSync({
    absWorkingDir: root,
    entryPoints: ['packages/core/src/browser.js'],
    bundle: true,
    platform: 'browser',
    format: 'iife',
    globalName: 'TrebuchetCore',
    target: 'chrome100',
    charset: 'utf8',
    legalComments: 'none',
    banner: { js: '// Generated by npm run build:js from @trebuchet/core/browser.' },
    write: false,
  }).outputFiles[0].text;
}

export function buildV2Js() {
  writeFileSync(v2AppPath, buildV2AppString());
  writeFileSync(browserCorePath, buildBrowserCoreString());
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) buildV2Js();
