#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const mod = (n) => join(root, 'public/modules', n);

// Concatenation order — must match original app.js structure.
// state.js and utils.js are reference files (extracted from preamble.js
// for navigation) and are not concatenated separately.
const modules = [
  'preamble.js',          // bind(), state, constants, flywheels, feeTiers
  'activity-log.js',      // log(), startServerLogStream(), setLoading(), withRunState()
  'confirm-dialog.js',    // confirmDialog()
  'release-notes.js',     // renderReleaseNotes() — update check UI
  'step-orchestrator.js', // setStepState(), activateStep(), bindStepHeaders()
  'cancel-flow.js',       // openCancelConfirm(), showCancelledPanel()
  'rpc-panel.js',         // loadRpcConfig(), renderRpcConfig(), selectRpc()
  'wallet-gen.js',        // wallet generation UI, mnemonic grid
  'token-config.js',      // validateLogoFile(), addPool(), renderSimpleConfig()
  'coin-preview.js',      // updateCoinPreview(), renderTokenPreview()
  'pool-editor.js',       // renderPools(), buildPoolNode(), cost preview, allocations
  'tokenomics.js',        // showTokenomicsModal(), donut chart
  'launch-report.js',     // buildLaunchReportHtml(), downloadLaunchReport(), launch success modal
  'funding.js',           // renderFundingRequirements(), startBalancePolling(), acquire flow
  'lp-execution.js',      // renderLpSummary(), LP creation, phase progress, lock summary
  'transfer.js',          // showTransferConfirmModal(), runTransfer()
  'journals.js',          // loadLaunchJournals(), buildLaunchJournalRow(), resume
  'pending-wallets.js',   // loadPendingWallets(), buildPendingWalletRow()
  'startup.js',           // setupDisclaimer(), setupSplashScreen(), startup gates
];

let out = '// app.js — built from modules/ by scripts/build-app-js.mjs\n// Edit modules/ — do not edit this file directly.\n\n';
for (const m of modules) {
  const content = readFileSync(mod(m), 'utf8');
  out += content;
  if (!content.endsWith('\n')) out += '\n';
  out += '\n';
}
writeFileSync(join(root, 'public/app.js'), out);
const kb = (out.length / 1024).toFixed(0);
console.log(`Built public/app.js from ${modules.length} modules (${kb} KB)`);
